image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.3:1NRvj3UKNTNwmYjptmUmIw==
    - ms-vscode.vscode-typescript-tslint-plugin@1.2.2:0nQ3PEEA0NPEt3UcbCYiIQ==
    - eamodio.gitlens@10.2.1:WIWu3zHU4VPT8r/v866LUw==
    - esbenp.prettier-vscode@5.0.0:eOsPTcR21+AQWEDGvWqMfA==

tasks:
  - init: npm install
    command: npm install -g @google/clasp && npm i -S @types/google-apps-script
